/**
 * store.ts — Redux store configuration.
 */

import { configureStore } from '@reduxjs/toolkit';
import { jingleApi } from '../api/jingleApi';
import { analysisSlice } from '../features/analysis/analysisSlice';
import { audioSlice } from '../features/audio/audioSlice';

export const store = configureStore({
  reducer: {
    // RTK Query API slice (auto-generated by createApi)
    [jingleApi.reducerPath]: jingleApi.reducer,

    // Local UI state slices
    analysis: analysisSlice.reducer,
    audio: audioSlice.reducer,
  },
  // RTK Query needs custom middleware to handle cache expiration
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(jingleApi.middleware),
});

export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
